esp_toml_version = 1.0

multipart = true
chip = "esp32-s3"
supported_apps = [ "ESP Agents Firmware: EchoEar" ]

["ESP Agents Firmware: EchoEar"]
icon = "https://github.com/espressif/esp-agents-firmware/wiki/images/EchoEarListening.jpeg"
image.esp32-s3.parts = [
  "https://esp-agents-firmware-prebuilt.s3.ap-northeast-1.amazonaws.com/friend/echo_ear/bootloader.bin",
  "https://esp-agents-firmware-prebuilt.s3.ap-northeast-1.amazonaws.com/friend/echo_ear/partition-table.bin",
  "https://esp-agents-firmware-prebuilt.s3.ap-northeast-1.amazonaws.com/friend/echo_ear/ota_data_initial.bin",
  "https://esp-agents-firmware-prebuilt.s3.ap-northeast-1.amazonaws.com/friend/echo_ear/esp_agent_voice_chat.bin",
  "https://esp-agents-firmware-prebuilt.s3.ap-northeast-1.amazonaws.com/friend/echo_ear/srmodels.bin"
]
image.esp32-s3.addresses = [ "0x0", "0x8000", "0x1c000", "0x30000", "0xe2c000" ]
readme.text = "https://raw.githubusercontent.com/espressif/esp-agents-firmware/refs/heads/main/docs/guides/echo_ear.md"

[[portConnectionOptions]]
console_baudrate = 115200
